### ISSUE TITLE
Sigma r not used in beverton-holt....?

### ISSUE THREAD

**Issue by msupernaw** [nmfs-fish-tools/RMAS#29]
Should we use bias correction or not? Make it optional?

Also, different formulation.
https://github.com/nmfs-fish-tools/RMAS/blob/master/src/mas/Recruitment.hpp#L276

MAS uses spawning biomass in the formulation

https://github.com/Bai-Li-NOAA/Age_Structured_Stock_Assessment_Model_Comparison/blob/master/R/OM_PopSim.R#L61

ASAP uses spawner_per_recruit

Also, MAS has a different formulation than the SDD

**Comment by Bai-Li-NOAA** [comment]
Make the bias correction optional sounds nice! I just checked the code, the B-H model from MAS, ASAP, and model comparison project OM are the same. 

The initial equilibrium numbers calculation looks different in MAS and OM, in particular, for plus group:

- MAS is designed to start with age 0 fish. [https://github.com/nmfs-fish-tools/RMAS/blob/b1920ae9b5075af1cc1e10565bb9e74e75aac8af/src/mas/Population.hpp#L665](https://github.com/nmfs-fish-tools/RMAS/blob/b1920ae9b5075af1cc1e10565bb9e74e75aac8af/src/mas/Population.hpp#L665)  
- Model comparison project OM: [https://github.com/Bai-Li-NOAA/Age_Structured_Stock_Assessment_Model_Comparison/blob/f63b9a751642cbfa05ba91e5398607461b5612cb/R/run_om.R#L113](https://github.com/Bai-Li-NOAA/Age_Structured_Stock_Assessment_Model_Comparison/blob/f63b9a751642cbfa05ba91e5398607461b5612cb/R/run_om.R#L113)
